application: chees-info
version: 1
runtime: go
api_version: go1

default_expiration: "1h"

handlers:
- url: /.well-known/acme-challenge/wVaspiZ4mbhzj9HktN0r7AediyqeHRkW4vuGAO8GVGI
  static_files: static/letsencrypt.txt
  mime_type: text/plain
  upload: static/letsencrypt.txt

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
  secure: always

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
  expiration: "1h"
  secure: always

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
  secure: always

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)
  secure: always

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  secure: always

- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"
  secure: always

- url: /(.+)
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
  expiration: "15m"
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "15m"
  secure: always
